---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - build-essential::default
      - start::default  # should run `./bin/librarian-chef install` before `kitchen converge`
    attributes:
